apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: {{ .Values.spec.containers.name }}
  name: {{ .Values.spec.containers.name }}
  namespace: {{ .Values.namespace.name }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: {{ .Values.spec.containers.name }}
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: {{ .Values.spec.containers.name }}
    spec:
      containers:
      - image: {{ .Values.image.repository }}:{{ .Values.image.tag }}
        imagePullPolicy: IfNotPresent
        name: {{ .Values.spec.containers.name }}
        resources:
          requests:
            cpu: 50m
            memory: 100Mi