apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: py-app
  namespace: app
spec:
  maxReplicas: 6
  minReplicas: 1
  scaleTargetRef:
    apiVersion: argoproj.io/v1alpha1
    kind: Rollout
    name: py-app
  targetCPUUtilizationPercentage: 90

