apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: {{ .Values.spec.containers.name }}
  namespace: {{ .Values.namespace.name }}    
spec:
  maxReplicas: 10
  minReplicas: 3
    scaleTargetRef:
      apiVersion: apps/v1
      kind: Deployment
      name: {{ .Values.spec.containers.name }}
    targetCPUUtilizationPercentage: 50 