apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: py-app
spec:
  maxReplicas: 10
  minReplicas: 3
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: py-app
  targetCPUUtilizationPercentage: 60
