apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: {{ .Values.service.name }}
    app.kubernetes.io/instance: py-app
  name: {{ .Values.service.name }}
  namespace: {{ .Values.namespace.name }}
spec:
  ports:
  - port: 80    
    protocol: TCP
    targetPort: 5000
  selector:
    app: {{ .Values.service.name }}
  type: NodePort
status:
  loadBalancer: {}