apiVersion: argoproj.io.v1alpha1
kind: Application
metadata:
  name: py-app
  namespace: argocd
spec:
  destination:
    namespace:
    server: https://kubernetes.default.svc
  project: default
  source:
    helm:
      valuesFiles:
      - values.yaml
      path: helm
      repoURL: https://github.com/N-Borisov/Cloud_Native/argocd
      targetRevision: HEAD