name: ci

on:
  push:
    branches:
      - 'main'
      - 'develop'
      - 'test'

jobs:
  build-push:
    env:
        IMAGE: bizzareniki/app.py
    runs-on: ubuntu-latest
    steps:
    # These are prerequisites for the docker build step
    - name: Generate build ID
      id: prep
      run: |
          branch=${GITHUB_REF##*/}          
          ts=$(date +%F.%H)
          echo "::set-output name=BUILD_ID::${branch}-${ts}"          

    - name: Set up QEMU
      uses: docker/setup-qemu-action@v2
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2
    - name: Login to DockerHub
      uses: docker/login-action@v2
      with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

    - name: Build and publish container image with tag
      uses: docker/build-push-action@v3
      with:
          push: true
          #context: .
          file: ./Dockerfile
          tags: |
                        ${{ env.IMAGE }}:${{ steps.prep.outputs.BUILD_ID }}
          build-args: PASS=${{ secrets.MYSQL_DATABASE_PASSWORD }}
                        
          